export interface MovieItem {
  title: string;
  genre: "comedy" | "drama" | "action" | "thriller";
  year: number;
  runtime: number;
  seen: boolean;
}

export const MOVIES: MovieItem[] = [
  {
    title: "The Matrix",
    genre: "action",
    year: 1999,
    runtime: 136,
    seen: true,
  },
  {
    title: "Napoleon Dynamite",
    genre: "comedy",
    year: 2004,
    runtime: 95,
    seen: false,
  },
  {
    title: "Office Space",
    genre: "comedy",
    year: 1999,
    runtime: 89,
    seen: false,
  },
  {
    title: "The Terminator",
    genre: "action",
    year: 1984,
    runtime: 107,
    seen: false,
  },
  {
    title: "Terminator 2: Judgment Day",
    genre: "action",
    year: 1991,
    runtime: 137,
    seen: false,
  },
  {
    title: "Raiders of the Lost Ark",
    genre: "action",
    year: 1981,
    runtime: 115,
    seen: false,
  },
  {
    title: "Good Will Hunting",
    genre: "drama",
    year: 1997,
    runtime: 126,
    seen: false,
  },
  {
    title: "The Godfather",
    genre: "drama",
    year: 1972,
    runtime: 175,
    seen: false,
  },
  {
    title: "The Hangover",
    genre: "comedy",
    year: 2009,
    runtime: 100,
    seen: false,
  },
  {
    title: "Die Hard",
    genre: "action",
    year: 1988,
    runtime: 132,
    seen: false,
  },
  {
    title: "Prisoners",
    genre: "thriller",
    year: 2013,
    runtime: 153,
    seen: false,
  },
  {
    title: "Gone Girl",
    genre: "thriller",
    year: 2014,
    runtime: 149,
    seen: false,
  },
  {
    title: "Eternal Sunshine of the Spotless Mind",
    genre: "drama",
    year: 2004,
    runtime: 108,
    seen: true,
  },
  {
    title: "The Sixth Sense",
    genre: "thriller",
    year: 1999,
    runtime: 107,
    seen: false,
  },
  {
    title: "Black Swan",
    genre: "thriller",
    year: 2010,
    runtime: 108,
    seen: true,
  },
  {
    title: "The Dark Knight",
    genre: "action",
    year: 2008,
    runtime: 152,
    seen: false,
  },
  {
    title: "Forrest Gump",
    genre: "drama",
    year: 1994,
    runtime: 142,
    seen: false,
  },
  {
    title: "The Silence of the Lambs",
    genre: "thriller",
    year: 1991,
    runtime: 118,
    seen: false,
  },
  {
    title: "No Country for Old Men",
    genre: "thriller",
    year: 2007,
    runtime: 122,
    seen: false,
  },
  {
    title: "The Social Network",
    genre: "drama",
    year: 2010,
    runtime: 120,
    seen: false,
  },
  {
    title: "Se7en",
    genre: "thriller",
    year: 1995,
    runtime: 127,
    seen: false,
  },
  {
    title: "Schindler's List",
    genre: "drama",
    year: 1993,
    runtime: 195,
    seen: false,
  },
  {
    title: "Psycho",
    genre: "thriller",
    year: 1960,
    runtime: 109,
    seen: true,
  },
  {
    title: "The Shawshank Redemption",
    genre: "drama",
    year: 1994,
    runtime: 142,
    seen: false,
  },
  {
    title: "The Pursuit of Happyness",
    genre: "drama",
    year: 2006,
    runtime: 117,
    seen: false,
  },
  {
    title: "Memento",
    genre: "thriller",
    year: 2000,
    runtime: 113,
    seen: false,
  },
  {
    title: "Gladiator",
    genre: "action",
    year: 2000,
    runtime: 155,
    seen: false,
  },
  {
    title: "Mad Max: Fury Road",
    genre: "action",
    year: 2015,
    runtime: 120,
    seen: false,
  },
  {
    title: "The Truman Show",
    genre: "drama",
    year: 1998,
    runtime: 103,
    seen: false,
  },
  {
    title: "Airplane!",
    genre: "comedy",
    year: 1980,
    runtime: 88,
    seen: true,
  },
  {
    title: "Lethal Weapon",
    genre: "action",
    year: 1987,
    runtime: 110,
    seen: false,
  },
  {
    title: "Speed",
    genre: "action",
    year: 1994,
    runtime: 116,
    seen: false,
  },
  {
    title: "John Wick",
    genre: "action",
    year: 2014,
    runtime: 101,
    seen: false,
  },
  {
    title: "The Departed",
    genre: "thriller",
    year: 2006,
    runtime: 151,
    seen: false,
  },
  {
    title: "Zodiac",
    genre: "thriller",
    year: 2007,
    runtime: 157,
    seen: false,
  },
  {
    title: "Superbad",
    genre: "comedy",
    year: 2007,
    runtime: 113,
    seen: false,
  },
  {
    title: "Anchorman: The Legend of Ron Burgundy",
    genre: "comedy",
    year: 2004,
    runtime: 94,
    seen: false,
  },
  {
    title: "Hot Fuzz",
    genre: "comedy",
    year: 2007,
    runtime: 121,
    seen: false,
  },
  {
    title: "Bridesmaids",
    genre: "comedy",
    year: 2011,
    runtime: 125,
    seen: true,
  },
  {
    title: "Super Troopers",
    genre: "comedy",
    year: 2001,
    runtime: 100,
    seen: true,
  },
  {
    title: "Ferris Bueller's Day Off",
    genre: "comedy",
    year: 1986,
    runtime: 103,
    seen: false,
  },
  {
    title: "The Grand Budapest Hotel",
    genre: "comedy",
    year: 2014,
    runtime: 99,
    seen: true,
  },
  {
    title: "Dumb and Dumber",
    genre: "comedy",
    year: 1994,
    runtime: 107,
    seen: false,
  },
  {
    title: "Goodfellas",
    genre: "drama",
    year: 1990,
    runtime: 146,
    seen: false,
  },
  {
    title: "The Prestige",
    genre: "thriller",
    year: 2006,
    runtime: 130,
    seen: false,
  },
  {
    title: "Shaun of the Dead",
    genre: "comedy",
    year: 2004,
    runtime: 99,
    seen: false,
  },
  {
    title: "American Beauty",
    genre: "drama",
    year: 1999,
    runtime: 122,
    seen: false,
  },
];
